# Generated by Django 5.1.2 on 2024-11-03 13:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship_post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScholarshipPostModelForm',
            new_name='ScholarshipPost',
        ),
    ]
