# Generated by Django 5.0.7 on 2024-11-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship_post', '0002_rename_scholarshippostmodelform_scholarshippost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshippost',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='scholarshippost',
            name='dead_line',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='scholarshippost',
            name='updated_at',
            field=models.DateField(),
        ),
    ]
