# Generated by Django 5.0.7 on 2024-11-23 14:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship_post', '0003_alter_scholarshippost_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshippost',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='scholarshippost',
            name='dead_line',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='scholarshippost',
            name='updated_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
