# Generated by Django 5.0.7 on 2024-11-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship_post', '0004_alter_scholarshippost_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarshippost',
            name='updated_at',
        ),
    ]
