# Generated by Django 5.1.6 on 2025-06-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship_post', '0006_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userImage', models.ImageField(upload_to='impact_images/')),
                ('userName', models.CharField(max_length=100)),
                ('scholarshipName', models.CharField(max_length=100)),
                ('studyProgram', models.CharField(max_length=100)),
                ('comments', models.TextField()),
            ],
        ),
    ]
