# Generated by Django 5.1.6 on 2025-06-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship_post', '0007_ourimpact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourimpact',
            name='userImage',
            field=models.ImageField(default='default.jpg', upload_to='impact_images/'),
        ),
    ]
