# Generated by Django 5.1.6 on 2025-06-17 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship_post', '0011_ourimpact_universityname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourimpact',
            name='comments',
        ),
    ]
