# Generated by Django 5.1.6 on 2025-06-18 23:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship_post', '0012_remove_ourimpact_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourimpact',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='ourimpact',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
