# Generated by Django 5.1.6 on 2025-06-18 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship_post', '0013_alter_ourimpact_options_ourimpact_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourimpact',
            options={},
        ),
    ]
