# Generated by Django 5.1.6 on 2025-06-18 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship_post', '0014_alter_ourimpact_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourimpact',
            options={'ordering': ['-date']},
        ),
    ]
