# Generated by Django 5.1.6 on 2025-06-18 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship_post', '0016_alter_ourimpact_options_remove_ourimpact_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact us'},
        ),
    ]
